# Generated by Django 4.2.4 on 2023-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc_autre',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_etat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_utilisation',
            field=models.TextField(blank=True),
        ),
    ]
