# Generated by Django 4.2.4 on 2023-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_promotion_alter_product_promotion_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion_prix',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
