# Generated by Django 4.2.4 on 2023-08-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scaledimage',
            old_name='scaled_image',
            new_name='scaled_image_100x100',
        ),
    ]
