# Generated by Django 4.2.4 on 2023-08-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_scaled_image_scaledimage_scaled_image_100x100'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaledimage',
            name='scaled_image_247x296',
            field=models.ImageField(default='', upload_to='scaled_images_247x296/'),
        ),
        migrations.AddField(
            model_name='scaledimage',
            name='scaled_image_510xH',
            field=models.ImageField(default='', upload_to='scaled_images_510xH/'),
        ),
        migrations.AlterField(
            model_name='scaledimage',
            name='scaled_image_100x100',
            field=models.ImageField(default='', upload_to='scaled_images_100x100/'),
        ),
    ]
