# Generated by Django 4.1.4 on 2023-08-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
