# Generated by Django 4.2.4 on 2023-08-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_index_page_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc_autre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_etat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_livraison',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_utilisation',
        ),
    ]
