# Generated by Django 4.2.4 on 2023-08-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_desc_autre_remove_product_desc_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_livraison_domicile', models.FloatField(default=0)),
                ('price_livraison_desk', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.wilaya')),
            ],
        ),
    ]
