# Generated by Django 4.2.4 on 2023-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_client_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prix',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='qte',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
